### ISSUE TITLE
Dashboard broke over time

### ISSUE THREAD

**Issue by james-munson** [WeebDev/lolisafe#102]
as you can see ive just uploaded an image and images before this but the dashboard stop updating, also no longer list what user uploaded the images. maybe my sqllitedb broke? and like 10+ commits behind so maybe this was fixed?

**Comment by Pitu** [comment]
Are you sure you uploaded the pictures while being logged in? That looks like an anonymous upload

**Comment by james-munson** [comment]
Randomly updating again.
