### ISSUE TITLE
Disabled Account

### ISSUE THREAD

**Issue by Giocovier** [WeebDev/lolisafe#104]
Apologies if wrong way to contact, 

Account created and used to act as easily accessible sound resource for kancolle notifications, believe frequent requests caused lockout from owned links. If this is against your use rules perfectly fine with that, just curious primarily.

**Comment by Pitu** [comment]
Almost every account was disabled since lolisafe.moe itself was intended as a demo of the platform for others to implement on their own. The files are still accessible and will remain so, but the accounts have been disabled to prevent further uploading.

**Comment by Giocovier** [comment]
Oh well damn, thank you for making it in the first place. It was good while it lasted, I think we're going to take what you have and host it internally and set up some external dns off my works registrar so we can have our own instance. 

Keep it up bud, thanks for it!!

**Comment by Shumatsu** [comment]
Check out other sites using lolisafe, they're listed in readme.
