### ISSUE TITLE
Question about nginx.conf

### ISSUE THREAD

**Issue by Qwerty-Space** [WeebDev/lolisafe#106]
Hello, 

I am setting up lolisafe on my Feral server.

I am using cloudflare, but I'm a bit confused about the paths in nginx.conf.  Do I add the paths from the root directory on the machine, or do I add the paths from the root directory of the site?

Most nginx setup is done automatically on Feral.

**Comment by Pitu** [comment]
Nginx config should have absolute paths from the machine, not the site

**Comment by Qwerty-Space** [comment]
Okay, thank you.
What about the index file?  When I go to my web page, all I see is the list of files in the directory.

**Comment by Qwerty-Space** [comment]
@Pitu my nginx.conf:

https://pastebin.com/uLysKFbZ

**Comment by RyoshiKayo** [comment]
Is lolisafe running on port 8830?

**Comment by Qwerty-Space** [comment]
@RyoshiKayo yeah, in config.js it's set to `port: 8830`

**Comment by RyoshiKayo** [comment]
But is it actually running in `pm2`?

**Comment by Qwerty-Space** [comment]
@RyoshiKayo yes

![image](https://user-images.githubusercontent.com/6967592/39554304-f7b240d2-4e69-11e8-97a3-39e5123270d2.png)

**Comment by RyoshiKayo** [comment]
Remove the index on line 22 of your nginx config.

**Comment by Qwerty-Space** [comment]
@RyoshiKayo done that, but it still just shows this:

![image](https://user-images.githubusercontent.com/6967592/39554418-926467ae-4e6a-11e8-8147-c156b1691a11.png)

**Comment by Duckbuster** [comment]
You did reload nginx after you removed the index line?
My config is mostly the same, but I also removed the root option in the / location.

Try nginx -t to make sure your config file is fine.

I think as I look at the pastebin you might have an issue with line 15 as well, since its not commented.

**Comment by Qwerty-Space** [comment]
Are you on Feralhosting too?

**Comment by Duckbuster** [comment]
No I'm not. Why would that be of relevance?

**Comment by Qwerty-Space** [comment]
Different setup
As it turns out nginx wasn't even loading that config file, so I moved it into a config file it was loading.

But it still doesn't work.

Updated config file in ~/.nginx:

```upstream backend {
    server 127.0.0.1:8830; # Change to the port you specified on lolisafe
}

server {
    listen 80;
    listen [::]:80;

    server_name va-online.moe;
    
    client_max_body_size 1024M; # Change this to the max file size you want to allow

    # Uncomment if  you are running lolisafe behind CloudFlare.
    # This requires NGINX compiled from source with:
    #     --with-http_realip_module
    # include /media/sdh1/home/qwertyspace/www/va-online.moe/public_html/real-ip-from-cf;

    location / {
        add_header Access-Control-Allow-Origin *;
        root /media/sdh1/home/qwertyspace/www/va-online.moe/public_html/uploads;
        try_files $uri @proxy;
    }

    # Pass files that end in .php to PHP
    location ~ \.php$ {
        fastcgi_read_timeout 1h;
        fastcgi_send_timeout 10m;

        include      /etc/nginx/fastcgi.conf;
        fastcgi_pass unix:/media/sdh1/home/qwertyspace/.nginx/php/socket;
    }

    # Deny access to anything starting with .ht
    location ~ /\.ht {
        deny  all;
    }

    location @proxy {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_pass http://backend;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_redirect off;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

#     include conf.d/va-online.d/*.conf;
#     # include /media/sdh1/home/qwertyspace/www/va-online.moe/public_html/nginx.conf;
# }
```

**Comment by Aareksio** [comment]
First off, check if the application runs correctly: `curl localhost:8830`
After you confirm application is running properly, check if nginx config is loaded:
```
location / {
	return 418;
}
```
You should see following error when visiting the site: `HTTP ERROR 418`, if you do, it's alright.
Rollback changes and simplify: `try_files @proxy`. 
If it works, rollback and try adding `autoindex off;`, as it seems to be `on` for some reason. That should solve the issue.

No matter if the above works or not, remove PHP execution from a file hosting please...
Also remove duplicate `proxy_redirect`.

**Comment by Qwerty-Space** [comment]
@Aareksio 
output of `curl localhost:8830`:
![image](https://user-images.githubusercontent.com/6967592/39583087-37ed0b1e-4ee7-11e8-8b4d-ca5db8e17be7.png)

Adding that to my nginx configuration didn't change anything

**Comment by Aareksio** [comment]
If adding `return 418` to configuration file didn't make it respons with `HTTP ERROR 418`, the configuration file is not loading properly.

Make sure after each change you execute `nginx -t` to check for errors and `nginx -s reload` to reload.

**Comment by Qwerty-Space** [comment]
@Aareksio I reloaded the config, and it didn't return 418

**Comment by Aareksio** [comment]
Then the configuration file is not being loaded, meaning it's neither lolisafe or example nginx config files fault, in other words, not an issue of this project.

**Comment by Qwerty-Space** [comment]
It should be being loaded.
I tested it was being loaded by including the nginx.conf from the lolisafe directory, and it didn't like some of the things from there.

**Comment by Pitu** [comment]
Closed as this doesn't seem to be an issue with lolisafe or the provided nginx config files. Feel free to reopen if that's not the case.
