### ISSUE TITLE
[Request] Option to remove EXIF data from uploads

### ISSUE THREAD

**Issue by RyoshiKayo** [WeebDev/lolisafe#110]
<strike>Add the ability to remove EXIF data from images on upload with https://github.com/hMatoba/piexifjs or something like it.</strike>

Add the option to remove EXIF data with `-strip` with GM.

**Comment by NadyaNayme** [comment]
Isn't graphicsmagick already used for thumbnails? It comes with [-strip](http://www.graphicsmagick.org/GraphicsMagick.html#details-strip) that removes EXIF data. No reason to add another dependency, IMO. 

Especially since there's already code to pipe into gm for generating thumbnails, could re-use similar code to pipe to gm to `-strip`.

**Comment by RyoshiKayo** [comment]
I would agree, if graphicsmagick actually worked on every distribution

**Comment by NadyaNayme** [comment]
Which distro are you using? I'm not aware of any UNIX or *BSD distros where it can't be built from source.

**Comment by RyoshiKayo** [comment]
@NadyaNayme See this issue: https://github.com/aheckmann/gm/issues/713

**Comment by NadyaNayme** [comment]
@RyoshiKayo I know these are probably silly questions, but I like to cover every base when debugging an issue. In your config.js for `lolisafe` have you set `generateThumbnails` to `true`? When you type `gm -v` in the console do you get an error or does nothing happen?

**Comment by RyoshiKayo** [comment]
Thank god you asked because I didn't know that was even an option.

**Comment by Pitu** [comment]
Closing this because my sides hurt

**Comment by RyoshiKayo** [comment]
This issue is still open :thinking:

**Comment by Pitu** [comment]
It's already implemented on the new version. Just wait for it.

**Comment by Pitu** [comment]
Decided against it. 
The whole point of lolisafe is not to modify users files, that's why for pictures we don't resize or compress, because I believe files should stay as uploaded.
