### ISSUE TITLE
IPV4 IP Problem

### ISSUE THREAD

**Issue by KroadD** [WeebDev/lolisafe#120]
Well , thanks for sharing this awesome source.It's really clean and nice.
But , I have a problem: 
 I can't open the hosting on my real ip addres.
 It's always on my localhost.
 Is there any way to change it?

Thanks for reading and have a good day!

**Comment by RyoshiKayo** [comment]
what

**Comment by KroadD** [comment]
I'm new at these things and I don't know how to setup it to my ipv4  ip instead of 127.0.0.1:9999

**Comment by RyoshiKayo** [comment]
You have to make a proxy with NGINX that points your domain to that port. Read the [readme page](https://github.com/WeebDev/lolisafe/blob/master/README.md)

**Comment by KroadD** [comment]
Thanks for your help I'm gonna try it right now!
