### ISSUE TITLE
Return Deletion URL from API

### ISSUE THREAD

**Issue by NadyaNayme** [WeebDev/lolisafe#123]
Return a deletion URL so that images may be deleted from ShareX without having to log in to the dashboard to delete things.

![](https://kimiwo.aishitei.ru/i/Ha2XhnMo1QbX0KiL.png)

**Comment by iamluca** [comment]
The deletion URL has already been made in the API. You will need to add it to the configuration file.

Upload Delete: https://github.com/WeebDev/lolisafe/blob/7711f0d45a9f10a8777573cc4ef5864386d74b35/routes/api.js#L21

Album Delete: https://github.com/WeebDev/lolisafe/blob/7711f0d45a9f10a8777573cc4ef5864386d74b35/routes/api.js#L30

**Comment by Pitu** [comment]
Uhhhh that is not what @NadyaNayme is asking. They want the delete url to be in the actual response of the upload route so that ShareX can use it.

**Comment by ImUrX** [comment]
Im not that experienced but isnt the deletion URL literally a shortcut for browser (in sharex)? then doesnt the Upload Delete in the api needs to be GET instead of PUT for making life easier for users?

**Comment by PascalTemel** [comment]
@NadyaNayms

**Comment by Pitu** [comment]
Implemented in 5b7dcc7, still needs revision since different database engines have the returning ID served different and mind that the route is not GET but DELETE, so I dont know if sharex handles that.

This should also take care of #175
