### ISSUE TITLE
A solution to support MWeb's image upload service

### ISSUE THREAD

**Issue by bing-e** [WeebDev/lolisafe#126]
[MWeb](http://www.mweb.im) is a markdown editor for MAC,it supports many image host services and also user-defined host.I tried to add `lolisafe` to the `MWeb` but failed.

The reason is that ` API JSON` responses  include file array urls like this 

```json
{
    "success": true,
    "files": [
        {
            "name": "zWifPHuxstt7SsvawfcbJoq38ZTxxR0Z.png",
            "size": "250121",
            "url": "http://files.xxx.com/zWifPHuxstt7SsvawfcbJoq38ZTxxR0Z.png"
        }
    ]   
}
```
The `files` is an array object,but we just need upload image one by one during the markdown writing.Due to that,`MWeb` can't parse the url directly.

So we need to modify code to add image url to the `JSON` without nesting in the array object.
### Modify code
I think the easiest way is to modify this file 

> controllers/uploadController.js

in this function

![-w100](http://files.bingestech.com/QyWokD3xxNNHMFaGaUcxuRHyBdkp8UNB.jpg)

add ```firstUrl:`${basedomain}/{existingFiles[0].name}` ``` to line 147

![-w100](http://files.bingestech.com/WHWUGd5uEX2XDfp8vIBTSZwK1PEKtsJQ.jpg)

Just echo an extra JSON object named `firstUrl`

### Setting MWeb
>-Preferences-Publishing

![-w400](http://files.bingestech.com/qgo0IdmATSUaGOJP5GHouwtpLwJsvVn4.png)
>-Custom

![Screen Shot-w400](http://files.bingestech.com/cZtZvMZGgfcFI1JevJrv8ZK7v4Jc15SV.png)

The `Response URL Path`'s value is we added in the code.

### About

That is my solution to do that,I think maybe someone need a perfect solution to use markdown editor with reliable image host service.I think MWeb+lolisale is  the best.

And i don't think modify API like this is a good idea,so i put an issue just for someone who need it.

**Comment by Pitu** [comment]
Next week I'm releasing a new version of lolisafe with a few breaking changes, and this issue that you mentioned is actually already taken care of. There's no need to return an array on the files uploaded if you uploaded just one. So hang in there and adding lolisafe to MWeb will be a cake walk starting next week.

**Comment by Pitu** [comment]
This is already implemented in dev. The response object when uploading a file is not an array anymore.
