### ISSUE TITLE
Can't change the token

### ISSUE THREAD

**Issue by oniyakun** [WeebDev/lolisafe#136]
When I installed lolisafe correctly, I click the **Request new token** button. 
But it not give me a new token, even others use the chrome extension and it will upload to my account. 
Idk whats wrong.

**Comment by oniyakun** [comment]
Sorry where I can find the console?
You mean DevTool's console or log directory?

**Comment by oniyakun** [comment]
Hummm... Seems no any log include error log

**Comment by oniyakun** [comment]
When I click the **Request new token** button it says “Your token was changed successfully”

**Comment by Pitu** [comment]
Yeah, that means your USER token has changed and no one can use the previous one. So I'm not sure what's the issue you are having :/

**Comment by oniyakun** [comment]
But I still can use the previous one to upload files
Sad

**Comment by Pitu** [comment]
That shouldnt be possible. Are you sure that by using a previous token, the uploads are getting tied to your user account? You may just have public uploads enabled and the file goes through even with a bad token (which is an issue that I'll have to fix, if this is true)

**Comment by oniyakun** [comment]
It's truly. Cuz I'm using the chrome extension to upload the file right now

**Comment by Pitu** [comment]
I'll do some tests and get back to you later.

**Comment by oniyakun** [comment]
Ok, very grateful

**Comment by oniyakun** [comment]
I got the error log

(node:24654) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Undefined binding(s) detected when compiling UPDATE query: update `users` set `token` = ?, `timestamp` = ? where `token` = ?

**Comment by oniyakun** [comment]
God you can‘t believe it.
When I use like ip:port to visit lolisafe, I found I can change the token.
But now, I can use all of the token, include previous and previous and previous token

(Not good at Eng, maybe I said not clearly, sorry

**Comment by Shumatsu** [comment]
What is your OS?
What is your node version?

**Comment by Shumatsu** [comment]
![Does the extension look like this?](https://lolisafe.moe/DhVy8N18.png)

**Comment by RyoshiKayo** [comment]
@oniyakun can you show your nginx config?

**Comment by oniyakun** [comment]
@Shumatsu 
CentOS7 with node 8.9.4
Yeh, its this extension

**Comment by oniyakun** [comment]
@RyoshiKayo I'm using Reverse Proxy to make lolisafe running with the ssl, did you mean reverse proxy's config?

**Comment by oniyakun** [comment]
Yeh its nginx, you need this nginx config?

**Comment by alucard0134** [comment]
i need to see the request thats being sent to the api, i doubt nginx would scrub out a request body in any way.

**Comment by Pitu** [comment]
If you can provide any more info feel free to re-open this.
