### ISSUE TITLE
How exactly do I disable an account?

### ISSUE THREAD

**Issue by Scotxd** [WeebDev/lolisafe#138]
Guy is looking like he won't pay me for hosting anymore, but he might still use the account. How do I disable it if I don't have his login info?

**Comment by RyoshiKayo** [comment]
Right now there is no way without manually editing the database. This may be implemented in the new version Pito is working on.

**Comment by Scotxd** [comment]
Ah. That sucks. I'll probably just edit the db for now. Hopefully I don't screw anything up. 🤷‍♂️

**Comment by Pitu** [comment]
Editing his token won't prevent him from generating another one if he logs in. You need a SQLite editor to modify the database, you can't do it like that.

**Comment by Kosemii** [comment]
A simple way to edit the database next time would be downloading the db file `lolisafe/database/db`;
Downloading [SQLiteBrowser](http://sqlitebrowser.org) and opening the db with the application.
You can use the browse data tab to quickly and easily find this user, then you'll want to change the `1` in the enabled column to a `0`.
Hope this helps :)

**Comment by Pitu** [comment]
You can also use dbeaver and make a direct connection to your server to open the db file, this way you can make sure you don't overwrite any data while you were downloading/uploading the db back to the server.

**Comment by Scotxd** [comment]
Thanks for the help, but he already paid me, albeit a bit late. I’ll remember this for next time though.
