### ISSUE TITLE
[Feature Request] DMCA notification system

### ISSUE THREAD

**Issue by iilukas** [WeebDev/lolisafe#145]
If someone reports an image and the admin marks it as a DMCA then it should send a notification to the user via email and on the dashboard notification system.

- make DMCA notification
- make notification button in dashboard
- make admin dashboard

**Comment by Pitu** [comment]
This is probably not gonna be a thing anytime soon. For starters, lolisafe doesn't ask for an email when signing up to the service in an attempt to hold as little personal information as possible, so the whole sending an email thing is already out of scope.

In most cases if you get hit with a dmca regarding a link, just delete it. Or not, depending how much of an anarchist you are.
