### ISSUE TITLE
[Feature Request] Extended Admin Dashboard

### ISSUE THREAD

**Issue by iilukas** [WeebDev/lolisafe#146]
This will extend the administrative dashboard for more functions.

- send notifications 
- docs notification system
- add admins
- username lookup
- database access
- maintenance mode
- add mod
- disable user
- ban ip
- ban email
- ban username
- disable access
- email verification system

**Comment by Pitu** [comment]
I'm down for:
* Disabling users
* Banning ips

The rest is a no-go for now, but you are welcome to submit a PR in the future with that functionality if you feel like coding it. Except the email thing, we don't do emails in lolisafe.

**Comment by iilukas** [comment]
Alright, thanks for that.

**Comment by iilukas** [comment]
What about adding additional admins could you do that through the database or what? Instead of having just one root admin user.

**Comment by gnosticJade** [comment]
There is no admin column in the users table. You could add it, but then you'd need to add a check for it in the code too. These are the only columns in the users table.
![image](https://user-images.githubusercontent.com/5164609/45244744-68645d00-b2b6-11e8-88f7-9ff1bf6674b6.png)

**Comment by iilukas** [comment]
How do you get into the DB?

**Comment by iilukas** [comment]
@gnosticJade @Pitu I believe more admins should be able to be added. There should be a way and it should be added in the rewrite. This is an enhancement.

**Comment by gnosticJade** [comment]
You are more than welcome to add it yourself in a fork and pull request it. There's plenty of other users, such as BobbyWibowo who forked it, added a feature they desired, and pull requested it into this branch. 
But realistically, there are slim to no reasons that I can see multiple admins is _necessary_ nor high priority.

**Comment by iilukas** [comment]
@gnosticJade If you have multiple staff members and don't want to login under `root`. I don't know how to add it that's why I am asking.

**Comment by Pitu** [comment]
For the time being there are no plans to support admins besides the root account. This might change in the future though.

**Comment by alucard0134** [comment]
only way @Pitu would do this is if you put a **PHAT** bug bounty on it
