### ISSUE TITLE
[Feature Request] Email Verification

### ISSUE THREAD

**Issue by iilukas** [WeebDev/lolisafe#147]
To verify and make sure people aren’t making false accounts and spamming the dB.

- email verify
- sends mailchip or using SMTP functions.
- IP information or device information viewable on the admin dashboard and gives browser information 
- IP information or device information viewable on dashboard that gives IP, and browser and operating system.

**Comment by Pitu** [comment]
This is not gonna be a thing.
We don't ask for emails, so sending email verification isn't gonna happen..
And if you are worried about the api/db getting spammed a ratelimit could be put in place, but you are suggesting something way more convoluted that I don't plan on adding for the time being.
