### ISSUE TITLE
Disabling users + Banning ips

### ISSUE THREAD

**Issue by iamluca** [WeebDev/lolisafe#152]
This has already been mentioned in https://github.com/WeebDev/lolisafe/issues/146#issuecomment-419273854 (#146).

@Pitu stated he was down for 
- [ ] Disabling users
- [ ] Banning IPs

in the new rewrite or release.

**Comment by iamluca** [comment]
No sense for banning IPs to be honest they could just get on a VPN. User banning is more better.

**Comment by Shumatsu** [comment]
And then they can make a new account on the same IP.

**Comment by Pitu** [comment]
This feature is already in the dev branch. Will move to master in the next release.
