### ISSUE TITLE
I'd like to implement exif data clearing upon upload.

### ISSUE THREAD

**Issue by t0nic** [WeebDev/lolisafe#155]
I am trying to implement it myself, but having trouble finding exactly where the files first come in so i can strip the exif data before anything else is done. Could a dev let me know where I need to look?  I have been looking in uploadController.js of course but im not sure...

**Comment by BobbyWibowo** [comment]
The file should already be in your `uploads` folder at [L75](https://github.com/WeebDev/lolisafe/blob/master/controllers/uploadController.js#L75) (accessible from `req.files`; there's even a forEach loop at [L87](https://github.com/WeebDev/lolisafe/blob/master/controllers/uploadController.js#L87)).
But it's probably best to do it before/after info of the file is being pushed into DB at [L110](https://github.com/WeebDev/lolisafe/blob/master/controllers/uploadController.js#L110). This bit of the code will only be executed if the uploaded file is a unique file (there's no existing file with exact same hash).

**Comment by RyoshiKayo** [comment]
Also note that this is being implemented in #110
