### ISSUE TITLE
Disable empty files and empty extensions

### ISSUE THREAD

**Issue by RyoshiKayo** [WeebDev/lolisafe#158]
As above, disable users from uploading empty files and files with empty extensions.

**Comment by iamluca** [comment]
I support this.

**Comment by Shumatsu** [comment]
Best way to support this is coding it in.

**Comment by PascalTemel** [comment]
Ill take a look at this when I have some free time this week

**Comment by Pitu** [comment]
Blocking empty extensions can be achieved by adding an empty string to the blockedExtensions array. I dont see the point in empty files though.
