### ISSUE TITLE
DB issue

### ISSUE THREAD

**Issue by iamluca** [WeebDev/lolisafe#160]
```
0|Images  | Unhandled Rejection (Promise): TypeError: this.where is not a function
0|Images  |     at Builder.db.table.where (/lolisafe-master/controllers/uploadController.js:856:14)
0|Images  |     at Formatter.compileCallback (/lolisafe-master/node_modules/knex/lib/formatter.js:210:14)
0|Images  |     at Formatter.rawOrFn (/lolisafe-master/node_modules/knex/lib/formatter.js:149:36)
0|Images  |     at QueryCompiler_SQLite3.whereWrapped (/lolisafe-master/node_modules/knex/lib/query/compiler.js:560:30)
0|Images  |     at QueryCompiler_SQLite3.where (/lolisafe-master/node_modules/knex/lib/query/compiler.js:350:32)
0|Images  |     at /lolisafe-master/node_modules/knex/lib/query/compiler.js:127:31
0|Images  |     at Array.map (<anonymous>)
0|Images  |     at QueryCompiler_SQLite3.select (/lolisafe-master/node_modules/knex/lib/query/compiler.js:126:33)
0|Images  |     at QueryCompiler_SQLite3.toSQL (/lolisafe-master/node_modules/knex/lib/query/compiler.js:74:27)
0|Images  |     at Builder.toSQL (/lolisafe-master/node_modules/knex/lib/query/builder.js:70:44)
0|Images  |     at /lolisafe-master/node_modules/knex/lib/runner.js:39:32
0|Images  |     at tryCatcher (/lolisafe-master/node_modules/bluebird/js/release/util.js:16:23)
0|Images  |     at /lolisafe-master/node_modules/bluebird/js/release/using.js:185:26
0|Images  |     at tryCatcher (/lolisafe-master/node_modules/bluebird/js/release/util.js:16:23)
0|Images  |     at Promise._settlePromiseFromHandler (/lolisafe-master/node_modules/bluebird/js/release/promise.js:512:31)
0|Images  |     at Promise._settlePromise (/lolisafe-master/node_modules/bluebird/js/release/promise.js:569:18)
```

**Comment by RyoshiKayo** [comment]
This literally tells me nothing.

**Comment by Pitu** [comment]
Since apparently you can't make the effort to provide a bit of context into what's happening, I checked `uploadController.js` on line 856 like the second line of your debug shows, and funny enough the uploadController on this repo only goes up to line 311.

So whatever is broken, it's on your own fork after you modified it.

**Comment by iamluca** [comment]
![image](https://user-images.githubusercontent.com/42306117/46566073-25fa6400-c8e6-11e8-95b3-0ed935d4e296.png)

**Comment by iamluca** [comment]
stream.on('end', async () => {
        const fileHash = hash.digest('hex');
        const dbFile = await db
          .table('files')
          .where(() => {
            if (user === undefined) {
              this.whereNull('userid');
            } else {
              this.where('userid', user.id);
            }
          })
          .where({
            hash: fileHash,
            size: info.data.size
          })
          .first();

        if (!dbFile) {
          if (
            info.data.albumid &&
            albumsAuthorized[info.data.albumid] === undefined
          ) {
            const authorized = await db
              .table('albums')
              .where({
                id: info.data.albumid,
                userid: user.id
              })
              .first();
            albumsAuthorized[info.data.albumid] = Boolean(authorized);
          }

          files.push({
            name: info.data.filename,
            original: info.data.originalname,
            type: info.data.mimetype,
            size: info.data.size,
            hash: fileHash,
            ip: req.ip,
            albumid: albumsAuthorized[info.data.albumid]
              ? info.data.albumid
              : null,
            userid: user !== undefined ? user.id : null,
            timestamp: Math.floor(Date.now() / 1000)
          });
        } else {
          utils.deleteFile(info.data.filename).catch(console.error);
          existingFiles.push(dbFile);
        }

        iteration++;
        if (iteration === infoMap.length) {
          resolve({ files, existingFiles });
        }
      });
    }
  });
};

uploadsController.scanFiles = async (req, infoMap) => {
  const dirty = await new Promise(async resolve => {
    let iteration = 0;
    const scanner = req.app.get('clam-scanner');
    const dirty = [];

    for (const info of infoMap) {
      const log = message => {
        console.log(`ClamAV: ${info.data.filename}: ${message}.`);
      };

      scanner.scanFile(info.path).then(reply => {
        if (!reply.includes('OK') || reply.includes('FOUND')) {
          log(reply.replace(/^stream: /, ''));
          dirty.push(info);
        }

        iteration++;
        if (iteration === infoMap.length) {
          resolve(dirty);
        }
      });
    }
  });

  if (!dirty.length) {
    return true;
  }

  // If there is at least one dirty file, delete all files
  infoMap.forEach(info =>
    utils.deleteFile(info.data.filename).catch(console.error)
  );
};

uploadsController.processFilesForDisplay = async (
  req,
  res,
  files,
  existingFiles
) => {
  const responseFiles = [];

  if (files.length) {
    // Insert new files to DB
    await db.table('files').insert(files);

    for (const file of files) {
      responseFiles.push(file);
    }
  }

  if (existingFiles.length) {
    for (const file of existingFiles) {
      responseFiles.push(file);
    }
  }

  // We send response first before generating thumbnails and updating album timestamps
  res.json({
    success: true,
    files: responseFiles.map(file => {
      return {
        name: file.name,
        size: file.size,
        url: `${config.domain}/${file.name}`
      };
    })
  });

  const albumids = [];
  for (const file of files) {
    if (file.albumid && !albumids.includes(file.albumid)) {
      albumids.push(file.albumid);
    }
    if (utils.mayGenerateThumb(pce(file.name).toLowerCase())) {
      utils.generateThumbs(file.name);
    }
  }

  if (albumids.length) {
    await db
      .table('albums')
      .whereIn('id', albumids)
      .update('editedAt', Math.floor(Date.now() / 1000))
      .catch(console.error);
  }
};

uploadsController.delete = async (req, res) => {
  const id = parseInt(req.body.id);
  req.body.field = 'id';
  req.body.values = isNaN(id) ? undefined : [id];
  delete req.body.id;
  return uploadsController.bulkDelete(req, res);
};

uploadsController.bulkDelete = async (req, res) => {
  const user = await utils.authorize(req, res);
  if (!user) {
    return;
  }

  const field = req.body.field || 'id';
  const values = req.body.values;

  if (!values || values.constructor.name !== 'Array' || !values.length) {
    return res.json({
      success: false,
      description: 'No array of files specified.'
    });
  }

  const failed = await utils.bulkDeleteFiles(field, values, user);
  if (failed.length < values.length) {
    return res.json({ success: true, failed });
  }

  return res.json({
    success: false,
    description: 'Could not delete any files.'
  });
};

uploadsController.list = async (req, res) => {
  const user = await utils.authorize(req, res);
  if (!user) {
    return;
  }

  let offset = req.params.page;
  if (offset === undefined) {
    offset = 0;
  }

  const files = await db
    .table('files')
    .where(() => {
      if (req.params.id === undefined) {
        this.where('id', '<>', '');
      } else {
        this.where('albumid', req.params.id);
      }
    })
    .where(() => {
      if (user.username !== 'root') {
        this.where('userid', user.id);
      }
    })
    .orderBy('id', 'DESC')
    .limit(25)
    .offset(25 * offset)
    .select('id', 'albumid', 'timestamp', 'name', 'userid', 'size');

  const albums = await db.table('albums').where(() => {
    this.where('enabled', 1);
    if (user.username !== 'root') {
      this.where('userid', user.id);
    }
  });

**Comment by iamluca** [comment]
```
d/js/release/promise.js:569:18)
0|Images  | Unhandled Rejection (Promise): TypeError: this.where is not a function
0|Images  |     at Builder.db.table.where (/lolisafe-master/controllers/uploadController.js:666:20)
0|Images  |     at Formatter.compileCallback (/lolisafe-master/node_modules/knex/lib/formatter.js:210:14)
0|Images  |     at Formatter.rawOrFn (/lolisafe-master/node_modules/knex/lib/formatter.js:149:36)
0|Images  |     at QueryCompiler_MySQL.whereWrapped (/lolisafe-master/node_modules/knex/lib/query/compiler.js:560:30)
0|Images  |     at QueryCompiler_MySQL.where (/lolisafe-master/node_modules/knex/lib/query/compiler.js:350:32)
0|Images  |     at /lolisafe-master/node_modules/knex/lib/query/compiler.js:127:31
0|Images  |     at Array.map (<anonymous>)
0|Images  |     at QueryCompiler_MySQL.select (/lolisafe-master/node_modules/knex/lib/query/compiler.js:126:33)
0|Images  |     at QueryCompiler_MySQL.toSQL (/lolisafe-master/node_modules/knex/lib/query/compiler.js:74:27)
0|Images  |     at Builder.toSQL (/lolisafe-master/node_modules/knex/lib/query/builder.js:70:44)
0|Images  |     at /lolisafe-master/node_modules/knex/lib/runner.js:39:32
0|Images  |     at tryCatcher (/lolisafe-master/node_modules/bluebird/js/release/util.js:16:23)
0|Images  |     at /lolisafe-master/node_modules/bluebird/js/release/using.js:185:26
0|Images  |     at tryCatcher (/lolisafe-master/node_modules/bluebird/js/release/util.js:16:23)
0|Images  |     at Promise._settlePromiseFromHandler (/lolisafe-master/node_modules/bluebird/js/release/promise.js:512:31)
0|Images  |     at Promise._settlePromise (/lolisafe-master/node_modules/bluebird/js/release/promise.js:569:18)
0|Images  | Unhandled Rejection (Promise): TypeError: this.where is not a function
````

**Comment by iCrawl** [comment]
Much like I thought, this isn't an issue with this version, but with @BobbyWibowo fork

https://github.com/BobbyWibowo/lolisafe/blob/safe.fiery.me/controllers/uploadController.js#L665

**Comment by iamluca** [comment]
Can I ask for assistance here or no?

**Comment by gnosticJade** [comment]
Does this look like Bobby's fork's issues?

**Comment by Pitu** [comment]
The issue is that you are losing `this` due to the function declaration at https://github.com/BobbyWibowo/lolisafe/blob/safe.fiery.me/controllers/uploadController.js#L662

**Comment by iamluca** [comment]
Fixed.

**Comment by iamluca** [comment]
@Pitu Something on my side. I've been changing some things recently and I formatted the code and knex didn't like it. 


I've added a manage users, multiple admins, device history, ban, unban, make admin, disable, enable account, etc.
