### ISSUE TITLE
Knex Connection Error

### ISSUE THREAD

**Issue by iamluca** [WeebDev/lolisafe#161]
Good afternoon,

I keep getting 
```
0|images   | Knex:warning - Connection Error: Error: Connection lost: The server closed the connection.
``` 
and was wondering how to resolve this issue

**Comment by Shumatsu** [comment]
Seems that your server dropped the connection.

Can't pinpoint how lolisafe would cause this though with a single error.

**Comment by iamluca** [comment]
Does the knex connection shutdown and not come back online?

**Comment by iamluca** [comment]
````2|discordi |               name: 0x2341ca482cd1 <String[9]: anonymous>
2|discordi |              msecs: 60000
2|discordi |  #17# 0x245d4881eb59: 0x245d4881eb59 <Object map = 0x1ebb631430d1>
2|discordi |               type: 0x33e4152af199 <String[10]: setTimeout>
2|discordi |         startAfter: 3442303
2|discordi |               name: 0x2341ca482cd1 <String[9]: anonymous>
2|discordi |              msecs: 6000
2|discordi |  #18# 0x245d4881e5f1: 0x245d4881e5f1 <JSArray[0]>
2|discordi |  #19# 0x245d4881e7d1: 0x245d4881e7d1 <JSArray[0]>
2|discordi | =====================
2|discordi |
2|discordi |
2|discordi | CodeObjects (0xdeadc0de length=6): 1:0x24e2ab204241 2:0x24e2ab2f04e1 3:0x24e2ab3a8ac1 4:0x24e2ab3a7a41...
2|discordi |    magic1=deadc0de magic2=deadc0de ptr1=0x2341ca482459 ptr2=(nil) ptr3=(nil) ptr4=(nil) ptr5=(nil) ptr6=(nil) ptr7=(nil) ptr8=(nil)
2|discordi |
````

**Comment by gnosticJade** [comment]
It comes back online if the database responds to subsequent attempts to access it. You could've answered this on your own, though:

- Does the service continue working after this error? How would it do that if the database is disconnected? (it wouldn't)?
- Even just a minute or two of Googling would tell you that the server dropped connection and there's little to nothing lolisafe can do about it.

And once again, you open issues providing absolutely 0 of the contextual code or configuration whilst using a completely different (and modified!) fork.

**Comment by Pitu** [comment]
@iamluca this looks like an issue with whatever database driver you are using. lolisafe ships with SQLite, so if you changed that might be worth checking that your other database is configured properly.
