### ISSUE TITLE
chunk uploading not working/bypassing cloudflare?

### ISSUE THREAD

**Issue by james-munson** [WeebDev/lolisafe#162]
when i upload a big file im getting
413 Request Entity Too Large
cloudflare

**Comment by Pitu** [comment]
That's because there is no chunk uploading currently.

**Comment by james-munson** [comment]
what about #87 you said it was added

**Comment by Pitu** [comment]
Yeah uh, it's added on the new version which is currently not on master yet. Delays and stuff.

**Comment by james-munson** [comment]
im using the new version with chunk support

**Comment by gnosticJade** [comment]
No, you're not. As Pitu said, it is not in the master branch.

**Comment by Pitu** [comment]
No you're not. Maybe from another fork, but not from master.

**Comment by james-munson** [comment]
Yeah its from a bobbys fork

**Comment by Pitu** [comment]
Then you should make an issue on that fork and not on master, which doesn't have that functionality built-in yet.
