### ISSUE TITLE
Swap graphicsmagick with sharp

### ISSUE THREAD

**Issue by PascalTemel** [WeebDev/lolisafe#168]
https://www.npmjs.com/package/sharp

Faster and doesnt require additional binaries to be installed

I might make a pull request for this soon unless someone else wants to do it

**Comment by Pitu** [comment]
Yeah sharp is really really good, I'm already using it to it's full extent on the rewrite, but it's not gonna be released any time soon since I'm swamped with work. But yeah, sharp is a green light from me.

**Comment by PascalTemel** [comment]
@Pitu Would a pull request be a waste since you're doing it anyway or should I go ahead with it? I'd imagine it's a pretty simple change

**Comment by Pitu** [comment]
It should be a simple change, you're free to make one :)

**Comment by PascalTemel** [comment]
Closing this since the PR was merged
