### ISSUE TITLE
Dashboard unconvinient thing

### ISSUE THREAD

**Issue by XCanG** [WeebDev/lolisafe#17]
As you know in Dashboard we have 2 view mode: table and thumbinal, but both unconvinient: table is bad because I can't know what is file is that (name is random, date not say much about it, album may be not used), thumbinal is bad because in that mode I don't know what is name of that thumbinal and I don't have delete button on it.

I suggest that to improve both: 
1) for table when hover on a line we will see baloon with thumbinal, so we can know what is image is that and it will not add extra space to a page.
2) for thumbinal mode when hover on thumbinal, at bottom we will see name of that thumbinal and at top-right will be appear delete button.

_P.S. sorry for my English if it hard to understand._

**Comment by alucard0134** [comment]
Im gonna make a PR for a fix for problem 1, but not too interested in 2 because i hate thumbnails ¯\_(ツ)_/¯

**Comment by iilukas** [comment]
No image on thumbnail.

**Comment by Pitu** [comment]
There's a new dashboard on dev branch, will merge into master and make a release this week
