### ISSUE TITLE
Upload with Shortcuts iOS 12

### ISSUE THREAD

**Issue by Scotxd** [WeebDev/lolisafe#187]
Since the Shortcuts app was added to iOS 12, I was wondering if there was a way to upload images to it. You can make POST requests to it, with headers, and the request body as "JSON" "Form" or "File". I can parse the JSON lolisafe returns myself, I just don't know how to get the upload working correctly. From my attempts, I get [this](https://i.imgur.com/hYNURy7.png) error.

**Comment by Pitu** [comment]
You got almost everything right. As seen on this [line](https://github.com/WeebDev/lolisafe/blob/master/controllers/uploadController.js#L46) you need to send the data in a field called `files[]` for the system to pick them up.

Let me know how it goes

**Comment by Scotxd** [comment]
It worked! Thank you!

**Comment by Pitu** [comment]
No problem!
