### ISSUE TITLE
Upload of large file fails in dev branch

### ISSUE THREAD

**Issue by Knallli** [WeebDev/lolisafe#188]
Dev branch throws
 `(node:29857) UnhandledPromiseRejectionWarning: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (1962924517) is greater than possible Buffer: 1073741823 bytes` 
when uploading a large file (above size of buffer) chunking is expected to prevent this

Chunking options in the .env file weren't touched
I raised the max size in .env and in the nginx site.conf

Screenshot of console output:
![image](https://user-images.githubusercontent.com/41125802/54044168-91ff3200-41ce-11e9-95be-9be29e5bc56d.png)

**Comment by Pitu** [comment]
Sorry for getting back to you so late, but this is being reworked on. You should not try to use the dev branch as a daily driver, at least with big files.

**Comment by Pitu** [comment]
This is no longer the case.
Solved in the dev release I'm pushing tonight
