### ISSUE TITLE
[BUG] Error at frontend after dashboard login

### ISSUE THREAD

**Issue by xaetacore** [WeebDev/lolisafe#203]
**Describe the bug**
If i login to the dashboard and after that go back to the frontend i get the following error pop up 
TypeError: Cannot set property 'innerHTML' of null

**To Reproduce**
1. Login to the dashboard
2. Click on 'Frontend'
3. See error

**Comment by Pitu** [comment]
Can you click on the error to show which line is causing it on the console?

**Comment by xaetacore** [comment]
I just managed to fix it.

somehow there were some lines missing. 
i just recloned it and it seems to work now lol.

Thanks anyways <3
