### ISSUE TITLE
[FEATURE REQUEST] Allow MySQL databases

### ISSUE THREAD

**Issue by Permanently** [WeebDev/lolisafe#207]
Just simply, allow the option to choose MySQL and the migration of SQLite to MySQL. This could be useful for those who set up multiple instances, but all want it linked to one database. Or, in my case, to keep all databases in one place that can be easily accessed and moderated, as well as to save space.

**Comment by Pitu** [comment]
You should be able to do that already by changing [this part of the config file](https://github.com/WeebDev/lolisafe/blob/master/config.sample.js#L99).
For possible values please check [the docs](http://knexjs.org/#Installation-client)

**Comment by Permanently** [comment]
Knew that part was there but didn't think there was any connection details - cheers x
