### ISSUE TITLE
Video thumbnails are not generating

### ISSUE THREAD

**Issue by fangshang132** [WeebDev/lolisafe#214]
**Describe the bug**
My video previews are enabled in the config.js and I have the `fluent-ffmpeg` installed, however, video previews are just showing up as the missing image icon.

**To Reproduce**
1. Go to uploads
2. Observe.

**Expected behavior**
See a video preview.

**Screenshots**
![](https://i.imgur.com/TiPsE2x.png)

**Comment by Pitu** [comment]
Do you have ffmpeg installed in your system?

**Comment by fangshang132** [comment]
Yes, I will try to reinstall it and refresh my instance.

**Comment by fangshang132** [comment]
> Yes, I will try to reinstall it and refresh my instance.

Fixed by reinstalling ffmpeg and refreshing instance.

**Comment by fangshang132** [comment]
Now that this is functioning correctly, is there a way to get thumbnails for previously uploaded files?

**Comment by Pitu** [comment]
Not built-in, but you can easily do it by making a script that loops over all the filenames of your uploaded files and calls [this method](https://github.com/WeebDev/lolisafe/blob/master/controllers/utilsController.js#L33) on each one

**Comment by 8cy** [comment]
don't know if you have already found a solution @fangshang132 but i came upon this thread and had this same problem myself. made [this](https://gist.github.com/8cy/8952fde31c0e36f06abd9e6999f4ceb0) simple script that should solve it.

**Comment by Pitu** [comment]
Yup, that'll do nicely

**Comment by Pitu** [comment]
[From the looks of it](https://gist.github.com/8cy/8952fde31c0e36f06abd9e6999f4ceb0#file-regeneratethumbnails-js-L2), just make sure you put it in the controllers folder, or any direct child folder from root.

**Comment by fangshang132** [comment]
thank you!

**Comment by alucard0134** [comment]
very cool, thanks kanye!
