### ISSUE TITLE
[BUG] Error when deploying to heroku.

### ISSUE THREAD

**Issue by Wishingirl** [WeebDev/lolisafe#222]
**Describe the bug**
Apparently, heroku cant read ./config.js
**To Reproduce**
1. Go to heroku
2. Create a new app and deploy lolisafe (Node 11)
3. Wait for the app to be sent.

**Expected behavior**
I expect it to simply work, but instead i got the error.

**Screenshots**
![image](https://user-images.githubusercontent.com/71225598/94180646-9b2e1d80-fe9e-11ea-95bf-2814fdd6c20b.png)

**Additional context**

**Comment by Pitu** [comment]
Make sure the command is ran from within the lolisafe folder and not outside of it

**Comment by Wishingirl** [comment]
`cd lolisafe && node lolisafe.js`?

**Comment by iCrawl** [comment]
Good luck deploying something that needs a filesystem to heroku. Heroku doesn't let you save files to a hard drive.

**Comment by Wishingirl** [comment]
Oh my bad
