### ISSUE TITLE
Adding sites to the wiki's site list is impossible

### ISSUE THREAD

**Issue by daniel11420** [WeebDev/lolisafe#223]
The sites list was moved from README.md to the GitHub Wiki for lolisafe, and the page says you can make a PR to add your site to it, but PRs aren't a thing on wikis (as far as I know. I googled and couldn't find anything either, just people saying its not a thing on wikis), so people can't add their site to the wiki.

**Comment by Pitu** [comment]
Very true, I'll move the list outside of the wiki again soon.
Thank you for bringing this up!

**Comment by daniel11420** [comment]
Not sure if you knew this but usually people close issues *after* addressing the problem...
