### ISSUE TITLE
[BUG] Error when running?

### ISSUE THREAD

**Issue by Wishingirl** [WeebDev/lolisafe#224]
**Describe the bug**
I cant seem to run the Lolisafe service.
**To Reproduce**
1. Git clone the project
2. cd lolisafe
3. npm i
4. change config.sample.js to config.js (also changed domain)
5. node lolisafe.js
(Using node 7.10.x)

**Expected behavior**
Start the lolisafe service.
**Screenshots**
![image](https://user-images.githubusercontent.com/71225598/98448119-4121a880-212a-11eb-8df3-2b2d1e9e9a40.png)

**Additional context**
I think it has to do with the SQL database.

My VPS runs:
30 gigs of ram
16 Vcores
300gb HDD
Ubuntu 20

**Comment by Pitu** [comment]
Just for the sake of checking, could you try running it with a more recent version of node like 12 or 14?

**Comment by Wishingirl** [comment]
I fixed the issue, i changed the version to 12 and reinstalled the whole thing, it's now up and running.

Also for the domain, i had to set it to ' '  if i wanted to run it from the ip, i know it's not intended.
