### ISSUE TITLE
File extension blacklist improvement

### ISSUE THREAD

**Issue by EpikPhailure** [WeebDev/lolisafe#42]
The blacklist can be easily bypassed by changing the case sensitivity of the extension.
For example, EXE instead of exe.

Parse the string in lowercases before making comparisons.

**Comment by Cryoplex** [comment]
Also, identification of filetype by mimetype may also be handy. We dont
want anyone upload an exe disguised as a jpg.

**Comment by Pitu** [comment]
I'll take a look at it, thanks for reporting this issue

**Comment by EpikPhailure** [comment]
I'll just make a PR since it's a 1 line fix
