### ISSUE TITLE
Not really a bug but an installation question. ><

### ISSUE THREAD

**Issue by INFLIGERE** [WeebDev/lolisafe#46]
So first of all, you have a great site. Much cleaner and nicer than pomf.

I've had some trouble installing it. I'm relatively new to server stuff. I seem to have everything working fine http://i.idgaf.fyi/ apart from when i upload, my links come out as http://i.idgaf.fyi/i.idgaf.fyi/ke3mHtZLQy8KIqsTjyGlAFz6oV4Z818i.jpg rather than http://i.idgaf.fyi/ke3mHtZLQy8KIqsTjyGlAFz6oV4Z818i.jpg 

Know where I went wrong? 

thank you for your time ><

**Comment by Pitu** [comment]
Sure! Can you show me your config file?

**Comment by INFLIGERE** [comment]
I think I figured it out. I changed the baseurl part ^^

**Comment by Pitu** [comment]
Great then, enjoy!

**Comment by B-rock-Code** [comment]
Hello, I just wanted to re-open this as I am having the same problem and I 1 other person I talked to about this had the same problem. The OP didn't give a very detailed response on how he fixed it, attached is my config file (yes, it's normally .js). If you want me to open up another report let me know as well.

Thank you for your help and work.

[config.txt](https://github.com/WeebDev/lolisafe/files/1313166/config.txt)

**Comment by Pitu** [comment]
Could you please tell me what should the final URL look like and how does it look like for you with this config?

**Comment by B-rock-Code** [comment]
Should be https://img.site.me/picture.png (I'd assume)

With this config, I get https://i.site.me/i.site.me/picture.png

I setup a subdomain for lolisafe under i.site.me.
server_name is i.site.me
location / {

**Comment by Pitu** [comment]
Try with
```js
domains: [
	{ host: 'img.site.me', resolve: 'https://img.site.me'},
]
```
Replace your domains array with this one and tell me if it works.

**Comment by B-rock-Code** [comment]
Same exact results. I restarted lolisafe.js and nginx service as well as hard refresh and tried a different browser. I will note that I am running this as root as well when uploading.

**Comment by Aareksio** [comment]
`config.domains[]` doesn't make the app serve files on `resolve` URL. In fact, it only ever serves on `/` ([source](https://github.com/WeebDev/lolisafe/blob/master/lolisafe.js#L28), have I mention it also ignores `config.uploads.folder`, which makes it break once you decide to change upload destination? [Oh, I have](https://github.com/WeebDev/lolisafe/issues/8#issuecomment-277472501)).  You have to do any redirection manually.

The `URL` is composed as following: `basedomain + '/' + file.name` ([source](https://github.com/WeebDev/lolisafe/blob/master/controllers/uploadController.js#L154)), where `basename` is `req.get('host')` or `resolve` part of matching `config.domains[]`. If you don't specify `resolve` or no matching domain is found - it'll compose something like `example.com/picture.png` - no protocol included. That's the reason why the link's destination is `https://i.site.me/i.site.me/picture.png` - `href` without a protocol, or at least two trailing slashes, is treated as relative.

If config sample from above (`{ host: 'img.example.com', resolve: 'https://img.example.com' }`) doesn't solve the issue (and your `host` matches real host), your application cannot properly read the `host` for some reason. 

Besides the bad, prone to such errors, design of the application, it's the problem with your forwarding software / other configuration.

**Comment by iCrawl** [comment]
The whole resolving should be on the nginx part anyway. Theres nearly no reason to have what the current design is, because as you mentioned it's prone to errors.
But as it stands right now this project is in a rewrite with a backend that's solid and structured. This project can be treated more as a side-project now since the major focus lies in the complete rewrite + rebranding.

**Comment by Pitu** [comment]
This [release](https://github.com/WeebDev/lolisafe/commit/5ff33ba93053b4e2127d79c75d95db6a702e8495) makes it possible to choose between node and nginx to serve files. If you want simplicity and your files at the root of your domain, set `serveFilesWithNode` to `true` in the config file. Otherwise set it to `false` and serve the files via nginx/apache manually. You can check the [sample nginx conf](https://github.com/WeebDev/lolisafe/blob/master/nginx.sample.conf) for guidance.
