### ISSUE TITLE
Set BaseURI?

### ISSUE THREAD

**Issue by genericsauce** [WeebDev/lolisafe#47]
Is there any way to set the baseURI for lolisafe? Right now if I have it reverse proxied to host.com/img and if I try to login it tries to go to host.com/auth instead of host.com/img/auth.

**Comment by Aareksio** [comment]
You can use nginx to achieve this, no need to alter the application.

```
location /img/ {
  ...
  proxy_pass http://safe/;
}
```

Notice the trailing slash, it'll do the work.

**Comment by genericsauce** [comment]
I am using Apache and tried to add a trailing slash but still have the issue of the redirects. Here is the proxy part of my Vhost
ProxyRequests Off 
    ProxyPreserveHost On
    ProxyPass /img/ http://genericsauce.site:9999/
    ProxyPassReverse /img/ http://genericsauce.site:9999/

**Comment by Aareksio** [comment]
Try experimenting with the slashes (eg. remove trailing one from `/img/`). When it comes to Apache I can't say more than quick Google search.

Once you find the answer, post it please, it may be helpful in the future.

**Comment by genericsauce** [comment]
Couldn't get it to work, ended up just making a new vhost.
