### ISSUE TITLE
[Feature suggestion] Automatically add new files in albums to a .zip and make it downloadable

### ISSUE THREAD

**Issue by PascalTemel** [WeebDev/lolisafe#48]
I'd like to let users download all files in an album. Now I could upload a zip of all the files that are in the album, however, I'd have to update that whenever I add files. I propose that all albums have a zip file that is hidden from the album view, but downloadable through a button. Of course, this would be optional and could be disabled in the config.

I'm not sure if anyone else is interested in this feature, but I might be able to make pull request for it if there's any interest.

**Comment by Pitu** [comment]
This is a pretty solid idea, I like it a lot. I've been in the process of rewriting lolisafe since yesterday and will make a new dev branch in the following hours if you want to take a look at it to try and figure a nice way of doing it!

**Comment by PascalTemel** [comment]
Sure, sounds good

**Comment by PascalTemel** [comment]
Just a heads up, I'll probably start working on this tomorrow, so if there's no dev branch pushed by then I'll go from master.

**Comment by PascalTemel** [comment]
Closing this since it's been implemented
