### ISSUE TITLE
Anonymous uploads through the API should be denied

### ISSUE THREAD

**Issue by EpikPhailure** [WeebDev/lolisafe#49]
Even with private mode disabled, nobody should be able to upload through the API UNLESS a valid token is specified. API uploading should only be allowed for users with registered accounts.

This may cause confusion for the administrator because he/she is unable to track who uploaded what.

Uploads using invalid tokens should be met with an error, or alternatively, something along the lines of having their uploads saved under a generic username such as "Anonymous".

IP logging is also very useful for administration purposes.

**Comment by iCrawl** [comment]
It would have to be your "alternative".
The whole point of pomf is that you upload stuff anonymously.

**Comment by Pitu** [comment]
As long as you keep private mode disabled, anyone will be able to upload anonymously.
