### ISSUE TITLE
[Feature suggestion] Add proper opengraph meta tags for albums

### ISSUE THREAD

**Issue by PascalTemel** [WeebDev/lolisafe#51]
Opengraph meta tags are used to generate previews for social platforms like facebook and discord. The bots that scrape this information do not execute javascript, so we can't change the tags once we have the album information - the information has to be there from the start.

I have a working but really ugly example for this feature locally. It uses prerender.io as a middleware and fetches the album information through a GET request in pages/album.html (express routing doesn't work apparently, so I can't do this in album.js), and then changes the tags. Problems with this implementation:
- It's REALLY ugly
- Users who want this feature would have to run their own prerender-node service locally or use the hosted prerender.io service, which might raise privacy issues

If you're interested in this feature I could show you what I've done and you could improve on it. Otherwise, feel free to just close this.

**Comment by Pitu** [comment]
Give me an hour to try a different approach that doesn't rely on having a node pre rendering endpoints just to get a preview of the content when pasting album links.

**Comment by Pitu** [comment]
Took a little bit more, but I made a new release with this. The way I decided to handle it is by rendering the route on the server and passing it to the user with the correct metadata, removing the api call from the page.
