### ISSUE TITLE
Manual Registration or when

### ISSUE THREAD

**Issue by XCanG** [WeebDev/lolisafe#52]
Can you manually register new users? I have some peoples what asked me how could they register on this website. I register on it before registration was closed.

Or when it will be possible again to register new users?

**Comment by Pitu** [comment]
If you're talking about https://lolisafe.moe, then registrations won't open again. I'm working on the next big update which will also include being able to create new users from an admin panel, so you can run it on your own and manage your userbase that way.

**Comment by XCanG** [comment]
Ok, a small question then, will you close site or not? If will do, I need to migrate to another and export my images stuff.

**Comment by Pitu** [comment]
No, there´s no plans for closing the site. It will remain active as long as I can maintain it.
