### ISSUE TITLE
safe.moe cipher suites shortage

### ISSUE THREAD

**Issue by sergeevabc** [WeebDev/lolisafe#59]
Upload test fails after importing [this file][1] with the existing token. Error log as follows:
```
Error: Message:
The request was aborted: Could not create SSL/TLS secure channel.

Request URL:
https://safe.moe/api/upload

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
```

[1]: https://safe.moe/sharex.txt

**Comment by EpikPhailure** [comment]
Should be resolved in commit https://github.com/WeebDev/lolisafe/commit/4ef19ed02734f52e74953d3697de065b458e4f02.

**Comment by sergeevabc** [comment]
Issue is not resolved, I see the same error.

**Comment by EpikPhailure** [comment]
Did you pull the latest commit?
Show us the contents of the ShareX file.

**Comment by sergeevabc** [comment]
Being a mere user and not a developer, I re-visited the website to find a fixed version, but found none.

**Comment by Aareksio** [comment]
`safe.moe` needs to update.

**Comment by Pitu** [comment]
@sergeevabc when you say website, are you referring to lolisafe.moe?
@Aareksio I'll let the owner know, but iirc safe.moe is several versions behind.

**Comment by sergeevabc** [comment]
@Pitu, I refer to the very link in the first message, i.e. https://safe.moe/sharex.txt

**Comment by Pitu** [comment]
@sergeevabc unfortunately I can't do anything about that except suggesting to the owner that they should update. The issue itself is solved in lolisafe as a service, so all that remains is for them to update.

**Comment by alucard0134** [comment]
this commit would not fix the issue the reporter is experiencing.

won't be pushing it downstream

**Comment by sergeevabc** [comment]
@alucard0134, so what are your thoughts on the cause of this issue?

**Comment by alucard0134** [comment]
it’s something related to sharex not liking the SSL ciphers and/or TLS version i’m passing to it. goto the sharex repo and report an issue and Jaex will help you out

**Comment by sergeevabc** [comment]
Dear @Jaex, could you investigate why ShareX 11.9 is able to import [this][1] destination file, but is not able to upload files because of the following error?

```
Error: Message:
The request was aborted: Could not create SSL/TLS secure channel.

Request URL:
https://safe.moe/api/upload

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
```

[1]: https://ghostbin.com/paste/3p4nm

**Comment by Jaex** [comment]
I can upload successfully: https://a.safe.moe/juHCx.png

Do you have .NET Framework 4.5 or newer version installed?

**Comment by sergeevabc** [comment]
@Jaex, with the help of [Raymondcc’s Detector][1], I am able to tell which .NET versions are installed:
```
.NET Framework 2.0 Service Pack 2
.NET Framework 3.0 Service Pack 2
.NET Framework 3.5 Service Pack 1
.NET Framework 4.6.2
```

[1]: https://www.raymond.cc/blog/how-to-check-what-version-of-microsoft-net-framework-is-installed-in-computer/

**Comment by sergeevabc** [comment]
Hmm, I tried to open ```safe.moe``` via IE 11 (reset to defaults beforehand, then even with SSLv2/v3 switched on) and faced an error message (not displayed by other browsers):
```
This page can’t be displayed

Turn on TLS 1.0, TLS 1.1, and TLS 1.2 in Advanced settings and try connecting to https://safe.moe  again. If this error persists, it is possible that this site uses an unsupported protocol or cipher suite such as RC4 (link for the details), which is not considered secure. Please contact your site administrator. 
```

**Comment by Pitu** [comment]
Could you please provide which Windows version are you using?

**Comment by sergeevabc** [comment]
@Pitu, Windows 7 x64. 

I did some via SSL Labs:
- SSL/TLS capabilities of [my IE 11][1]
- [see][2] the handshake simulation part of the ```safe.moe``` report (their IE11 bot on Win 7 fails as well) 

[1]: http://images.vfl.ru/ii/1510335135/accb18e2/19365423.png
[2]: https://www.ssllabs.com/ssltest/analyze.html?d=safe.moe

**Comment by alucard0134** [comment]
what ciphers is nginx offering you

**Comment by sergeevabc** [comment]
@alucard0134, actually it blows my mind to find out the _only one_ cipher suite ```safe.moe``` currently supports is ```TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256```. No wonder IE11 on Win7 cannot access it.

The right thing to do here is to follow some TLS deployment best practice (e.g. [this one][1] by SSL Labs).

[1][https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices#23-use-secure-cipher-suites]

**Comment by alucard0134** [comment]
wot in tarnation i’ll fix dat inna sec

**Comment by alucard0134** [comment]
following the mozilla's modern security suite recommendations i appended it to my config, no idea why my dumbass didnt catch that my bad

**Comment by sergeevabc** [comment]
Hereby I confirm that both IE11 and ShareX on Windows 7 can access ```safe.moe``` without errors.
