### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by kevinvdburgt** [WeebDev/lolisafe#60]
Is there any interest of docker support? If so, I would be glad to create a pull request for this 'feature'!

**Comment by Pitu** [comment]
That sounds like a wonderful idea. I've never personally worked with docker but if it makes it easier for people to deploy then I'm all in!

**Comment by kevinvdburgt** [comment]
@Pitu Docker just rocks! You really should try messing around with it :)

There is a PR being made, so this issue can be closed: https://github.com/WeebDev/lolisafe/pull/64
