### ISSUE TITLE
Add custom IP header support

### ISSUE THREAD

**Issue by binuwu** [WeebDev/lolisafe#70]
There should be support for custom headers (when tracking IPs) for flexibility. Common header names include `X-Real-IP`, `X-Forwarded-For`, `CF-Connecting-IP`, and etc.

As some people won't use NGINX, some may use Apache, IIS, or just run it directly in a load-balanced environment and also behind reverse proxies such as CloudFlare, CloudFront, Flatly, Voxel, or KeyCDN.

Please also allow host verification when running without a reverse proxy, and send a 400 Bad Request when data that isn't properly formatted as an HTTP Request is sent to the Transmission Control Protocol Pipeline. Examples may include just some dude typing out `telnet lolisafe.moe 80` and then typing out random characters.

**Comment by Pitu** [comment]
On the [Sample NGINX conf](https://github.com/WeebDev/lolisafe/blob/master/nginx.sample.conf) that I provide, both `X-Real-IP` and `X-Forwarded-For` are already there. This already works with lolisafe, so you can use whatever server you decide and as long as you provide these headers lolisafe should just grab them 👍 

Regarding the verification on the second part of your post, you are welcome to open a PR and contribute to it! 🎉

**Comment by binuwu** [comment]
that's some good shit 👀 👍 :tm:
