### ISSUE TITLE
Dashboard Problems

### ISSUE THREAD

**Issue by hyperdefined** [WeebDev/lolisafe#76]
Hello!

When I go to my dashboard and click any links on the side, it just says "There was an error with the request, please check the console for more information."

I didn't change anything, I installed it and logged in.

Also, when I go back to the home page, it logs me out no matter what.

**Comment by Shumatsu** [comment]
What error showed up in console?

**Comment by hyperdefined** [comment]
Nothing shows up in my console. There is nothing under the log folder either.

**Comment by hyperdefined** [comment]
Wonder if there is a problem with my auth at all.

**Comment by hyperdefined** [comment]
Alright, you now stay logged in when going back to the home page. The dashboard still has the same problem, clicking any buttons says there was an error. Nothing still shows up in console for some reason.

**Comment by Pitu** [comment]
@hyperdefined can you open devtools, go to the Network tab and show me the Preview tab when you click on the `Uploads` menu item on the side? The request should look something like this ![](https://lolisafe.moe/UFBEsXWI.png)

**Comment by hyperdefined** [comment]
![chrome_2018-02-25_12-15-08](https://user-images.githubusercontent.com/13475823/36644271-a1699b30-1a25-11e8-97da-488acdb9f13b.png)

Also, now it says this in the console when I click Change your password"
![chrome_2018-02-25_12-16-31](https://user-images.githubusercontent.com/13475823/36644280-bab324b2-1a25-11e8-86e5-e19d0dd20e88.png)

**Comment by Pitu** [comment]
Would you mind joining the Discord server for lolisafe, so I can take a closer look at your issue? Because right now I'm super lost as what could be causing your issue.

**Comment by hyperdefined** [comment]
Problem solved. Stupid me removed the div on the dashboard that loads the content.
