### ISSUE TITLE
Page not found.

### ISSUE THREAD

**Issue by Zejk** [WeebDev/lolisafe#79]
Soo, when I upload file to the server and open link of it, says me error 'Page not found.'

**Comment by Pitu** [comment]
Soo, you'll have to provide more details for us to he able to help you.

Can you supply your config file, show/tellnus how did you setup nginx and where on disk are you saving lolisafe/uploads?

**Comment by alucard0134** [comment]
my mother provides me w more info than this when she needs help, maybe hosting a file hosting site isnt for you

**Comment by Pitu** [comment]
Since OP never bothered to provide additional data, I'm losing this.
