### ISSUE TITLE
Thumbnails lead to 404

### ISSUE THREAD

**Issue by hyperdefined** [WeebDev/lolisafe#80]
Thumbnails seem to be broken or don't work at all.
The thumbs folder is empty, even after I upload files.

Copying the uploads to the thumbs folder solves it, but I would like to know why it doesn't make them automatically.

**Comment by Pitu** [comment]
Is there any error on the console at the moment you upload a file?

**Comment by hyperdefined** [comment]
Nope, no errors in the console.

**Comment by alucard0134** [comment]
is graphicsmagick installed

**Comment by hyperdefined** [comment]
Yes, I have it installed. 

Running nginx on Ubuntu 16.04.4.

**Comment by Pitu** [comment]
This is pretty weird. May I suggest installing `imagemagick` instead and modifying [this line](https://github.com/WeebDev/lolisafe/blob/master/controllers/utilsController.js#L4) so it looks like

```js
const gm = require('gm').subClass({imageMagick: true});
```
And see if it works?

**Comment by hyperdefined** [comment]
Adding that line fixed it. Dunno why I need to do that but it works now!
