### ISSUE TITLE
Uploaded Images Page Not Found

### ISSUE THREAD

**Issue by VulgarBear** [WeebDev/lolisafe#81]
Hello, I installed with the directions provided and everything appears to be up and running. I can access the site, login, upload screenshots via ShareX but am unable to actually access my photos. Not completely sure what I did wrong.

* Copy of config https://pastebin.com/Ugb1zQFz
* Copy of nginx file https://pastebin.com/1mDFTxiX

**Comment by FOG-Yamato** [comment]
```nginx
upstream backend {
	server 127.0.0.1:8080;
}

server {
	listen 80;
	listen [::]:80;

	server_name image.shisify.com;

	client_max_body_size 512M;

	location / {
		add_header 'Access-Control-Allow-Origin' '*';
		root /root/lolisafe/uploads;
	}

	location @proxy {
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Host $http_host;
		proxy_set_header X-NginX-Proxy true;
		proxy_pass http://backend;
		proxy_redirect off;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_redirect off;
		proxy_set_header X-Forwarded-Proto $scheme;
	}
}
```
Here is your new config, this should serve the files from your lolisafe folder aswell as work on the actual lolisafe app.

**Comment by VulgarBear** [comment]
This passed the test but removing the `try_files $uri @proxy;` line caused a 504 error.

**Comment by Pitu** [comment]
I see that your config file points the uploads directory to `/lolisafe/uploads` . Is this correct? Is it actually on the file system's root?

**Comment by VulgarBear** [comment]
Currently yes, doing so just for easy testing before moving to a better location on another server.

**Comment by Pitu** [comment]
Since it's not on your home folder or some place relevant like that, are you sure the uploads folder has the right permissions to be readable by everyone?

**Comment by VulgarBear** [comment]
Okay so I moved the directory to /var/www/lolisafe/uploads just to be safe and that seemed to do the trick

**Comment by Pitu** [comment]
It was most likely a problem with the folder's permissions. If you need any further help don't hesitate to comment further. Glad it's working!

**Comment by VulgarBear** [comment]
No problem, I'm still wrapping my head around nginx so shit happens.

**Comment by RyoshiKayo** [comment]
Depending on how how you installed NGINX, if you wanted to put the files `/lolisafe/uploads/` you would have to give the folder 755 and add www-data (Or whatever group you have NGINX running as) to the folder.

```bash
# Change Permissions:
sudo chmod -Rv 770 /lolisafe/uploads

# Change group:
sudo chown -R <user>:www-data /lolisafe/
# where <user> is the user you're running lolisafe under.
