### ISSUE TITLE
Option to delete uploads when deleting an album.

### ISSUE THREAD

**Issue by Shumatsu** [WeebDev/lolisafe#82]
Sometimes I create albums that later I don't need. Deleting all those uploads one by one is a pain. Would be nice to make it possible to delete albums along with their contents.

**Comment by PascalTemel** [comment]
This is something I want aswell. I might try to make a PR for this sometime soon™.

**Comment by RyoshiKayo** [comment]
@PascalTemel FYI Kana is currently rewriting the entire project, so I'd wait a couple weeks before making a PR

**Comment by PascalTemel** [comment]
Thanks for the info, guess Ill wait.

**Comment by Pitu** [comment]
Already implemented in dev
