### ISSUE TITLE
Allow root acccount to manage accounts from the dashboard

### ISSUE THREAD

**Issue by hyperdefined** [WeebDev/lolisafe#83]
There could be a list of accounts, and we could ban/delete/etc them from the dashboard.

Also have the option to make an account from there.

**Comment by Pitu** [comment]
This is definitely something we should have

**Comment by iilukas** [comment]
Any update on this feature?

**Comment by iilukas** [comment]
Refer to #146

**Comment by Pitu** [comment]
This is already implemented in dev branch
