### ISSUE TITLE
Enhance public albums

### ISSUE THREAD

**Issue by RyoshiKayo** [WeebDev/lolisafe#89]
In addition to #27 add the following:

- View permissions based on account (Requires #39 )
- Ability to contribute to another users album, and have the owner of that album able to have an accept/reject ability for the contribution.

**Comment by Pitu** [comment]
While this is not gonna be implemented for now, there is a feature coming that will let you create individual links to albums and set them to expire, so you can share different links with different people and not give them lifelong access.
