### ISSUE TITLE
Toggle for Registrations

### ISSUE THREAD

**Issue by AnonVodka** [WeebDev/lolisafe#90]
Can you add an option to disable/enable registartions/creating accs via the root account on the dashboard. Would be cool.

**Comment by Pitu** [comment]
That functionality is only tied to the root account, so it seems kind of pointless to have an extra setting to enable or disable that.
Could you explain to me why you need this? What's the use case?

**Comment by AnonVodka** [comment]
Im kind of an lazy person and everytime i want someone to register i'd need to change it, in the config file, to true, wait for them to register and set it to false afterwards. Since i want to keep it "private" that would make things way easier.

**Comment by Pitu** [comment]
I understand what you're saying. In the near future, root accounts will be able to create new users without having to change the toggle on the config file, so you can look forward to that 👍
