### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by AnonVodka** [WeebDev/lolisafe#98]
I recorded a video via sharex, tried to upload it via sharex and the upload stopped and i had huge ram usage. My ram usage is usually at ~400MB - ~700MB, on my vps, after trying to upload it went up to 3.8GB.

before uploading:
https://gyazo.com/5e8f326d7f90b6ea7331bae374668775

while uploading:
https://gyazo.com/bfead2505b4d696b1c6a66dcdb83bd28

Only happens sometimes, not sure why and what could cause that.

**Comment by RyoshiKayo** [comment]
That's not really a memory leak, memory leaks are usually persistent throughout the lifetime of the process.
I can try monitoring my instance but in all honestly this looks normal.

**Comment by RyoshiKayo** [comment]
Also those screenshots look like system memory usage not just for lolisafe :eyes:

Like Alucard said it's probably just NGINX.
